### ISSUE TITLE
misc issues after .989 update

### ISSUE THREAD

**Issue by Filu2259** [Keriew/augustus#1590]
C3 model: 
the model data for large temples and senate has changed.

new figures:
large temple: 150;6;1;2;3;5
Senate: 400;8;2;-1;8;30

instead of previously
large temple: 150;14;2;-2;5;5
senate: 400;8;2;-2;6;30

Also in the model, alternative native huts, native huts, and native centers have a cost in Denarii.

Compatibility:
.sav files (the vanilla format) have become incompatible
edit: .map too

Misc:
defeat timer is expressed in "years" and "favor lost if not fulfilled 1 to 12" instead of "years" and "months 1 to 12".

**Comment by Johannes-callidus** [comment]
With the Large temples you are correct but I'm very sure that the desirability range of the senate always was 8. That the timer is now measured in year is a feature because who wants to read 532 months until defeat.

**Comment by Sephirex95** [comment]
we can check those model values. 
do you have a screenshot of that favour thing in the timer? Sounds very odd

**Comment by Johannes-callidus** [comment]
I checked, I'll corect the temples but the Senate is right.

**Comment by Filu2259** [comment]
It is not possible to launch the vanilla campaign.

**Comment by Filu2259** [comment]
<img width="446" height="87" alt="Image" src="https://github.com/user-attachments/assets/573c19c0-bec3-4c3c-9a03-0b46e1e1a479" />

**Comment by Filu2259** [comment]
ok for the senate, it was a misconception taken from http://mmxl.wz.cz/c3a/structures.html + brainfog i guess

**Comment by Johannes-callidus** [comment]
> It is not possible to launch the vanilla campaign.

I can launch it but it doesn't quiet do what I expected.
To quote @Sephirex95 "worked on first attempt, slay" Are you sure?

**Comment by Filu2259** [comment]
<img width="808" height="350" alt="Image" src="https://github.com/user-attachments/assets/e88022d3-5699-4a2c-b82c-b5e5a10c2cef" />

[augustus-log.txt](https://github.com/user-attachments/files/23426686/augustus-log.txt)

**Comment by Filu2259** [comment]
Also got a game crash when loading a random save in my list. other saves seem to work.


[Filu wheat only 94 fav.zip](https://github.com/user-attachments/files/23426704/Filu.wheat.only.94.fav.zip)


edit making sure to add the good log: 

[augustus-log.txt](https://github.com/user-attachments/files/23426730/augustus-log.txt)

**Comment by Sephirex95** [comment]
> > It is not possible to launch the vanilla campaign.
> 
> I can launch it but it doesn't quiet do what I expected. To quote [@Sephirex95](https://github.com/Sephirex95) "worked on first attempt, slay" Are you sure?

I am sure. It worked on first attempt, Filus attempt is at least second if not third.
Who checks compatibility with vanilla campaign on a 10k+/- lines PR 🤣 

I'll fix it tomorrow

**Comment by Sephirex95** [comment]
> <img alt="Image" width="446" height="87" src="https://private-user-images.githubusercontent.com/228659320/511559925-573c19c0-bec3-4c3c-9a03-0b46e1e1a479.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI1NTU0MDEsIm5iZiI6MTc2MjU1NTEwMSwicGF0aCI6Ii8yMjg2NTkzMjAvNTExNTU5OTI1LTU3M2MxOWMwLWJlYzMtNGMzYy05YTAzLTBiNDZlMWUxYTQ3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwN1QyMjM4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzFmY2U4ODY5ZjUxZWQ0NmYxMmJhMTM0YzE5N2JiNjhmYmQ0Mjc2NzlhZjVlYzM4NDExOWFhYzJkOTAwMjAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i6aVSx16o0LGJWHUsNmifLpsuMddirraj2k_L1kmAgM">

this is probably overzealous translation ID fix. My bet is on translation id +1 bump

**Comment by Filu2259** [comment]
crash after trying to start valentia in the CCK

[augustus-log.txt](https://github.com/user-attachments/files/23427843/augustus-log.txt)

**Comment by Johannes-callidus** [comment]
Okay so it crashes when assigning the icons as far as I can say.

**Comment by Johannes-callidus** [comment]
fixed

**Comment by Filu2259** [comment]
Mentioned by citybuilderbob on discord and I checked in one of my cities with augustus .995

Medium insula now devolve to small insula if they don't have barber access. Medium insula normally require doctor access, and large insula barber access.

**Comment by Johannes-callidus** [comment]
I know I have typed in all those values by hand that's why I'm very glad people are reporting those issues.
#1594

**Comment by Filu2259** [comment]
still unable to load .sav, unable to start  vanilla campaign, and crash when loading valentia cck

[augustus-log.txt](https://github.com/user-attachments/files/23433206/augustus-log.txt)

**Comment by Johannes-callidus** [comment]
Well, my PR hasn't merged yet so it's not in the master yet.

**Comment by Filu2259** [comment]
okay ^^ sorry (did you catch the barber thing?)

edit: ofc you did. thanks a lot ^^

**Comment by Filu2259** [comment]
What's strange is that i crash loading valentia cck, but not with the other cck original maps

**Comment by Johannes-callidus** [comment]
It has something to do with City names in original empires.
That's why it's different from map to map.

**Comment by Filu2259** [comment]
Was it necessary to use the new city icons for old maps? its kind of weird to have major cities randomly represented as villages, I must say ^^. I'll use them to make my empire beautiful though!

**Comment by Johannes-callidus** [comment]
You are only able to specify them in custom empires on other ones they are randomly assigned. But you can get a new random assignment of them by restarting.

**Comment by Filu2259** [comment]
random idea but they could be assigned based on trade volume in denarii or cartloads 59/ 60-119/ 120+, and land/sea?

**Comment by Johannes-callidus** [comment]
I like it currently only cities called "Rome" or something similar are getting special icon. @Sephirex95 What do you think?

**Comment by Filu2259** [comment]
I have a small hovel Syracusae ^^
And Massilia and Lugdunum

**Comment by Sephirex95** [comment]
We might do something about the assignments before 4.5, but ATM I'm in favour of more or less random allocation to help us catch any visual glitches or adjustments necessary.
Will close this for now, any particular bugs - raise a new issue please, group issues like this one are difficult to track
