### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jachoo** [Keriew/augustus#788]
Description: game crashes :(

How to reproduce:
1. load the attached save file
2. immediately increase speed to 200%
3. game usually crashes after a few seconds

Augustus version: 3.2.0.198 (Polish)
OS: Windows 11

Log, augustus.ini and save file attached.
[crash_report2.zip](https://github.com/Keriew/augustus/files/10305317/crash_report2.zip)

**Comment by crudelios** [comment]
I've pushed a fix to a similar issue yesterday.

Please try the latest unstable, hopefully it fixes your problem!

**Comment by PrettyFlower** [comment]
I tested this out and it still seems to be happening. Somehow a ship got a last_visited_index of 2 but the visited_buildings array has length 1 so it ends up loading an invalid visited_building.

**Comment by crudelios** [comment]
Was that right after load? Can you get me the save please?

**Comment by jachoo** [comment]
I tested on the latest Augustus 3.2.0.212 - the game still crashes the same way (load -> increase speed to 200% -> crash). Save file and logs are attached to the first post.

**Comment by PrettyFlower** [comment]
@crudelios  Save is in the original crash_report2.zip file but I've reattached it here for clarity. It happens shortly after load if you increase the game speed.

[bug.zip](https://github.com/Keriew/augustus/files/10314748/bug.zip)

**Comment by jachoo** [comment]
@PrettyFlower without speed increase, the game sometimes still crashes (it depends on speed, zoom, scroll, clicks, etc.)

**Comment by PrettyFlower** [comment]
@jachoo The speed increase (or zoom, scroll, etc) aren't really related. Once the ship tries to access a visited_building outside the bounds of the array, the behavior is undefined so it's really only a matter of time before the game crashes. Fortunately it starts making bad memory accesses shortly after the game loads (no speed increase necessary). The real trick is figuring out how the ship got a last_visited_index outside the bounds of the array.

![image](https://user-images.githubusercontent.com/2081059/209831724-0067d1ac-e919-4420-ba8e-173dc6231601.png)

**Comment by crudelios** [comment]
This may have been some leftover bug from before the crashfix.

@jachoo Here's your save right after the crashing point, I fixed it for you. Please let us know if it crashes again.

[bug2.zip](https://github.com/Keriew/augustus/files/10316986/bug2.zip)
